/* AUTO-GENERATED by scripts/sync-drive-images.mjs — do not edit */
import type { CategoryData } from './categories'

export const CATEGORIES: CategoryData[] = [
  {
    id: "circular-floral-backdrop",
    lines: [
      "Circular Floral",
      "Backdrop",
    ],
    cardImage: "/gallery/circular-floral-backdrop/18X9tHcABBYIwCgT8c6ne6KJSYndqnz0x.webp",
    galleryTitle: "Circular Floral Backdrop",
    photos: [
      "/gallery/circular-floral-backdrop/18X9tHcABBYIwCgT8c6ne6KJSYndqnz0x.webp",
      "/gallery/circular-floral-backdrop/1DPbe0i5QnVCdIkwy0IjwonT1gS7c-y4q.webp",
      "/gallery/circular-floral-backdrop/1ngcY_gh8TqOZqxcUDotb5JiV_u6p2c9F.webp",
      "/gallery/circular-floral-backdrop/1R4M_KT12Kg6hGby_OVbta_Ljt-iMLlqC.webp",
      "/gallery/circular-floral-backdrop/13hixT9IpJny-OqNc9gTEeDCIPuzJUtxN.webp",
    ],
  },
  {
    id: "circular-round-backdrop",
    lines: [
      "Circular Round",
      "Backdrop",
    ],
    cardImage: "/gallery/circular-round-backdrop/1PXQMh1YYkeXwGKj6dhuiCBv1Yqzn0EjF.webp",
    galleryTitle: "Circular Round Backdrop",
    photos: [
      "/gallery/circular-round-backdrop/1PXQMh1YYkeXwGKj6dhuiCBv1Yqzn0EjF.webp",
      "/gallery/circular-round-backdrop/1rN2G_lsx-m6qZS_kwOzID3NzgK1CqTWV.webp",
      "/gallery/circular-round-backdrop/1lHEmKyunc7O8UQ604RHBveGdRXZGNR70.webp",
      "/gallery/circular-round-backdrop/1xXaK4VMlq8dQcQlcRerXzh73RDLae2r3.webp",
      "/gallery/circular-round-backdrop/1f7DRbci8Tr4w1vV_TY2fHR4tqA6_osLG.webp",
    ],
  },
  {
    id: "hanging-toran",
    lines: [
      "Hanging Toran",
    ],
    cardImage: "/gallery/hanging-toran/1j2z8XXV9M6IWzEZne2QLQS47yjVXDUbD.webp",
    galleryTitle: "Hanging Toran",
    photos: [
      "/gallery/hanging-toran/1j2z8XXV9M6IWzEZne2QLQS47yjVXDUbD.webp",
      "/gallery/hanging-toran/1W4zaKXfWPWjmqtuqJLTWcS10TuLbC7AQ.webp",
      "/gallery/hanging-toran/1tbO9m24wJZzUvFmSIYFMRSuWPBRrRiEy.webp",
      "/gallery/hanging-toran/179kWHXuxvClJzj0Wv-KsU1VwEWx6tO73.webp",
      "/gallery/hanging-toran/1u7kOK52f81gwC94xT50sl5Ck5P9PjlWB.webp",
    ],
  },
  {
    id: "modak-pushp-backdrop",
    lines: [
      "Modak Pushp",
      "Backdrop",
    ],
    cardImage: "/gallery/modak-pushp-backdrop/1khNUOH8zI6guJfI0wZ8aaPhN_sjc311x.webp",
    galleryTitle: "Modak Pushp Backdrop",
    photos: [
      "/gallery/modak-pushp-backdrop/1khNUOH8zI6guJfI0wZ8aaPhN_sjc311x.webp",
      "/gallery/modak-pushp-backdrop/1oBEmAoe8-XTVVfwQz7oGu5lDTIKivMUk.webp",
      "/gallery/modak-pushp-backdrop/1sZyI1JZkKZ3keEl9XR17uxeCYWgT6KE4.webp",
      "/gallery/modak-pushp-backdrop/1iyeh00VE3IKQfeVLtF8GBZCqfv4bn3ZL.webp",
      "/gallery/modak-pushp-backdrop/1E4CoiYMbWTdM0p9efggd0IkS--VmbL65.webp",
    ],
  },
  {
    id: "standing-still-backdrop",
    lines: [
      "Standing Still",
      "Backdrop",
    ],
    cardImage: "/gallery/standing-still-backdrop/1SM1lDzdSetXD-3IMDqIMRPlfZHkJJFBw.webp",
    galleryTitle: "Standing Still Backdrop",
    photos: [
      "/gallery/standing-still-backdrop/1SM1lDzdSetXD-3IMDqIMRPlfZHkJJFBw.webp",
      "/gallery/standing-still-backdrop/1gxh3yoFvD0vcvAmzk_tlYFQ6YgfZoH0H.webp",
      "/gallery/standing-still-backdrop/18dWvOGSdwK3k8OJtDzdh5Eqt6-5g3MRX.webp",
      "/gallery/standing-still-backdrop/1nrKbIbiqwDmceGkDMfc0tsF3O_wTjgo6.webp",
      "/gallery/standing-still-backdrop/1JfRI0MCmD-RRqvOg1iCTSXkBVn6v8iOi.webp",
    ],
  },
]
